# Generated by Django 5.0.6 on 2024-06-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('parameter_name', models.TextField()),
                ('parameter_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Test_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chose', models.TextField()),
                ('returned', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.student_result')),
            ],
            options={
                'unique_together': {('result', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Inf_Exam_Frawork_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.inf_exam_framework')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.lesson')),
            ],
            options={
                'unique_together': {('exam', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Lesson_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.lesson')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.request')),
            ],
            options={
                'unique_together': {('lesson', 'request')},
            },
        ),
        migrations.CreateModel(
            name='Test_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.test')),
            ],
            options={
                'unique_together': {('question', 'test')},
            },
        ),
    ]
