# Generated by Django 5.0.6 on 2024-06-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0002_parameter_detail_test_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_lesson',
            name='total',
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=40)),
                ('value', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.topic')),
            ],
            options={
                'unique_together': {('keyword', 'topic')},
            },
        ),
    ]
