# Generated by Django 5.0.6 on 2024-06-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0003_remove_question_lesson_total_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proportion_student',
            name='total',
        ),
        migrations.AlterField(
            model_name='proportion_student',
            name='percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student_result',
            name='score',
            field=models.FloatField(),
        ),
    ]
