# Generated by Django 5.0.6 on 2024-06-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0004_remove_proportion_student_total_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detail_test_student',
            unique_together=set(),
        ),
    ]
