# Generated by Django 5.0.6 on 2024-06-20 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0005_alter_detail_test_student_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.classroom'),
        ),
        migrations.CreateModel(
            name='ClassroomResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.classroom')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.topic')),
            ],
            options={
                'unique_together': {('classroom', 'topic')},
            },
        ),
    ]
