# Generated by Django 5.0.6 on 2024-07-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0007_test_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inf_exam_framework',
            name='exam_name',
            field=models.CharField(max_length=255),
        ),
    ]
