# Generated by Django 5.0.6 on 2024-07-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0008_alter_inf_exam_framework_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_question',
            name='times',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
