# Generated by Django 5.0.6 on 2024-06-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('book_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inf_Exam_Framework',
            fields=[
                ('exam_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exam_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField()),
                ('question_level', models.IntegerField()),
                ('date_update', models.DateTimeField(null=True)),
                ('date_create', models.DateTimeField(null=True)),
                ('picture', models.BinaryField(null=True)),
                ('form', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.TextField()),
                ('class_name', models.CharField(max_length=10)),
                ('picture', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lesson_name', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.booktype')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('answer_content', models.TextField()),
                ('answer_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('test_name', models.TextField()),
                ('date_update', models.DateTimeField()),
                ('date_create', models.DateTimeField()),
                ('factor', models.IntegerField()),
                ('numer_q', models.IntegerField()),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.inf_exam_framework')),
            ],
        ),
        migrations.CreateModel(
            name='Student_result',
            fields=[
                ('result_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.test')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('percent', models.CharField(max_length=10)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.topic')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.topic'),
        ),
        migrations.CreateModel(
            name='Question_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.lesson')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.question')),
            ],
            options={
                'unique_together': {('question', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Question_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.question')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.request')),
            ],
            options={
                'unique_together': {('question', 'request')},
            },
        ),
        migrations.CreateModel(
            name='Proportion_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.request')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.student')),
            ],
            options={
                'unique_together': {('student', 'request')},
            },
        ),
        migrations.CreateModel(
            name='Question_BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.question')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.topic')),
            ],
            options={
                'unique_together': {('question', 'topic')},
            },
        ),
    ]
