# Generated by Django 5.0.6 on 2024-07-25 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0009_test_question_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.lesson')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.test')),
            ],
            options={
                'unique_together': {('test', 'lesson')},
            },
        ),
        migrations.DeleteModel(
            name='Inf_Exam_Frawork_Lesson',
        ),
    ]
