# Generated by Django 5.0.6 on 2024-06-21 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0006_classroom_alter_student_class_name_classroomresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HeThongHoTroLT.student'),
        ),
    ]
