# Generated by Django 5.0.6 on 2024-07-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeThongHoTroLT', '0011_student_result_times_delete_test_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_time',
            field=models.IntegerField(null=True),
        ),
    ]
